#!/bin/sh

#
# include common functions, variables...
#
source /usr/lib/cgi-bin/stf/xml/bin/common.sh

#
# remove old temp files...
#
rm -f /tmp/dhtab.[0-9]+

echo "Content-type: text/html"
echo ""
echo "<html><body>"
cd /usr/lib/cgi-bin/stf/xml/bin

java alloff domhub2.lbl.gov

echo "<h2>Done</h2>"
echo "</body></html>"
