#!/bin/sh

#
# show the run-tests html page...
#
source /usr/lib/cgi-bin/stf/xml/bin/common.sh

echo "Content-type: text/html"
echo

#
# get parameter name...
#
test=`echo $QUERY_STRING | qryParam testname`

qry=`printf \
    "select \
      STFTestType.name, STFParameter.name, STFParameter.is_output, \
      STFParameterType.name, STFParameter.default_value, \
      STFParameter.min_value, STFParameter.max_value \
     from \
      STFTest, STFTestType, STFTestParameter, STFParameter, \
      STFParameterType \
     where \
      STFTestType.name='%s' and \
      STFTestType.stf_testtype_id=STFTest.stf_testtype_id and \
      STFTestParameter.stf_test_id=STFTest.stf_test_id and \
      STFParameter.stf_param_id=STFTestParameter.stf_param_id and \
      STFParameter.stf_paramtype_id=STFParameterType.stf_paramtype_id \
     order by STFParameter.name;" ${test}`

exec ${mysqlcmd} "${qry}" | awk -f ${awkpath}/dbtestfixup.awk | \
    awk -v test=${test} -f ${awkpath}/tabtoqry.awk

