#!/bin/sh

#
# include common functions, variables...
#
source /usr/lib/cgi-bin/stf/xml/bin/common.sh

echo "Content-type: text/html"

#
# check for a pick and an existing session...
#
pick=`echo ${QUERY_STRING} | qryParam pick`
stfsession=`echo $HTTP_COOKIE | qryCookie stfsession`
if [[ ${#pick} == 0 || ${#stfsession} == 0 ]]; then
    #
    # no pick or no session, we need to start a new session...
    #
    if [[ ${#stfsession} != 0 ]]; then
	closeSession ${stfsession}
    fi
    stfsession=`newSession`
    echo "Set-Cookie: stfsession=${stfsession}"
fi

#
# setup new tab file...
#
if [[ ! -f /tmp/stf/${stfsession}/dhtab ]]; then
    stfmode > /tmp/stf/${stfsession}/dhtab
fi

#
# check for a pick...
#
if [[ ${#pick} != 0 ]]; then
    setPick ${pick}
fi

#
# done with header...
#
echo

#
# display the table...
#
exec awk -v pick=${pick} -f ${awkpath}/dhservertab.awk \
    /tmp/stf/${stfsession}/dhtab
