#!/bin/sh

#
# plot-array plot an xml results file...
#
source /usr/lib/cgi-bin/stf/xml/bin/common.sh

#
# get xml filename...
#
fname=`echo $QUERY_STRING | qryParam file`
qry=`printf "select text from STFResultXML where stf_result_id=%s" ${fname}`

#
# get parameter name...
#
param=`echo $QUERY_STRING | qryParam parameter`

if ${mysqlcmd} "${qry}" | xmln | awk -f ${awkpath}/restotab.awk | \
    awk "\$2 ~ /${param}/ { print \$3; }" >& /tmp/data.$$; then
    #
    # create an R script...
    #
    echo "setwd('/tmp')" > /tmp/$$.R
    echo "v <- scan('data.$$');" >> /tmp/$$.R
    echo "bitmap(file='plot.$$.png')" >> /tmp/$$.R
    echo "plot(v, ylab='${param}', type='l')" >> /tmp/$$.R
    echo "graphics.off()" >> /tmp/$$.R

    if R CMD BATCH /tmp/$$.R /tmp/$$.Rout; then
	echo "Content-type: image/png"
	echo
	cat /tmp/plot.$$.png
    else
	echo "Content-type: text/html"
	echo
	echo "<h2>Error running plotting program</h2><pre>"
	cat /tmp/$$.Rout
	echo "</pre>"
    fi
    rm -f /tmp/plot.$$.png /tmp/$$.Rout /tmp/$$.R
else
    echo "Content-type: text/html"
    echo
    echo "<h2>Error</h2><pre>"
    cat /tmp/data.$$
    echo "</pre>"
fi

rm -f /tmp/data.$$







