#!/bin/sh 

source /usr/lib/cgi-bin/stf/xml/bin/common.sh

#
# validate parameters from a qry...
#
if [[ $# != 3 ]]; then
    echo "usage: validate-param testname paramname value"
    exit 1
fi

cmd="/^$1\t$2\tinput\t/ { \
    if ( \$4 == \"unsignedInt\" && \
	( (\$6 != \"\" && $3 < \$6 ) || \
	  (\$7 != \"\" && $3 > \$7 ) )) \
	  print \"parameter \" \$2 \" is invalid, expecting \
	    [\" \$6 \", \" \$7 \"]\"; \
    }"

exec awk "$cmd" /var/www/stf/xml/all.tab
