#!/bin/bash

#
# stf-client: run the stf client...
#
if [[ "`which java`" == "" ]]; then
    echo "`basename $0`: can not find java executable"
    exit 1
fi

#
# make sure domhub-tools is current enough...
#
dv=`domhub-version | awk '{ print $3; }'`
if [[ "${dv}" == "" ]]; then
    echo "`basename $0`: can not find domhub tools version number"
    exit 1
fi

if (( ${dv} < 200 )); then
    echo "`basename $0`: domhub-tools version is too old, we need 200+"
    exit 1
fi

#
# set the classpath from the jars in the jars directory...
#
cp=`/usr/bin/lessecho ./jars/*.jar | tr ' ' ':' | sed 's/:$//1'`

#
# return ',' separated list of doms
#
function domlist() {
    domstate all | awk '$2 ~ /^iceboot$/ { print $1; }' | tr '\n' ',' | \
	sed 's/,$//1'
}

#
# parse arguments...
#
# echo "usage: `basename $0` [--doms=CWD[,CWD...]] stfargs"
#
doms=""
origargs="$*"
opts=`getopt -q -l 'doms:' -- 'd:' $*`
set -- $opts
while /bin/true; do
    if [[ $1 == "--doms" || $1 == "-d" ]]; then
	# good...
	domlist=T
	shift
    elif [[ $1 == "--" ]]; then
	shift
	break
    fi
    shift
done

if (( ${#domlist} == 0 )); then
    iceboot all > /dev/null
    doms="--doms=`domlist`"
fi

if (( ${#doms} == 0 )); then
    echo "`basename $0`: no doms found..."
    exit 1
fi

#
# run stf...
#
exec java -classpath "${cp}" icecube.daq.stf.STF ${doms} $origargs
