#!/bin/sh

#
# include common functions, variables...
#
source /usr/lib/cgi-bin/stf/xml/bin/common.sh

echo "Content-type: text/html"

#
# get current picks from cookie or set default (first
# in servers file...
#
stfserver=`echo $HTTP_COOKIE | qryCookie stfserver`
if [[ ${#stfserver} == 0 ]]; then
    stfserver=`head -1 ${xmlpath}/servers | awk '{print $1}'`
fi

stfport=`echo $HTTP_COOKIE | qryCookie stfport`
if [[ ${#stfport} == 0 ]]; then
    stfport=`head -1 ${xmlpath}/servers | awk '{print $2}'`
fi

#
# check for picks and echo to cookies on browser...
#
pick=`echo $QUERY_STRING | qryParam stfserver`
if [[ ${#pick} != 0 ]]; then
    echo "Set-Cookie: stfserver=${pick}"
    stfserver=${pick}
fi

pick=`echo $QUERY_STRING | qryParam stfport`
if [[ ${#pick} != 0 ]]; then
    echo "Set-Cookie: stfport=${pick}"
    stfport=${pick}
fi

#
# done with header...
#
echo

#
# display the table...
#
awk -v stfserver=${stfserver} -v stfport=${stfport} -v xmlpath=${xmlpath} \
    -f /usr/lib/cgi-bin/stf/xml/bin/servertab.awk \
    ${xmlpath}/servers









