#!d:\apps\msys-1.0\bin\sh.exe

#
# set proper path...
#
xpath=/e/apps/xerces-c2_1_0-win32/bin
xpath=${xpath}:/e/apps/xml-xalan/c/Build/Win32/VC6/Release
PATH=/usr/bin:/d/apps/msys-1.0/bin:/d/apps/mingw/bin:/e/arthur/xml/bin:${xpath}

xmlpath=e:\\arthur\\xml

#
# view-summary
#
echo "Content-type: text/html"
echo

echo "<html>"
echo "  <head>"
echo "    <title>Summary</title>"
echo "  </head>"
echo "  <body>"

awk -f /e/arthur/xml/bin/sumtotable.awk /e/arthur/xml/summary

echo "  </body>"
echo "</html>"
