#!d:\apps\msys-1.0\bin\sh.exe

#
# include common routines/variables
#
source /e/arthur/xml/bin/common.sh

#
# view-summary
#
echo "Content-type: text/html"
echo

echo "<html>"
echo "  <head>"
echo "    <title>Summary</title>"
echo "  </head>"
echo "  <body>"

#
# FIXME: check for parameters -- add link to search...
#
awk -f /e/arthur/xml/bin/sumtotable.awk /e/arthur/xml/summary

#
# FIXME: search code goes here...
#

echo "  </body>"
echo "</html>"
